format = """
$all$fill$username$localip$line_break\
$character"""

[fill]
symbol = " "

[character]
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold white)"

[username]
disabled = false
show_always = true
format = '[$user]($style)'

[localip]
disabled = false
ssh_only = false
format = '@[$localipv4]($style) '

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[azure]
symbol = "az "
format = '[$symbol($subscription)]($style) '

[buf]
symbol = "buf "
format = '[$symbol($version )]($style)'

[bun]
symbol = "bun "
format = '[$symbol($version )]($style)'

[c]
symbol = "C "
format = '[$symbol($version(-$name) )]($style)'

[cobol]
symbol = "cobol "
format = '[$symbol($version )]($style)'

[conda]
symbol = "conda "
format = '[$symbol$environment]($style) '

[crystal]
symbol = "cr "
format = '[$symbol($version )]($style)'

[cmake]
symbol = "cmake "
format = '[$symbol($version )]($style)'

[daml]
symbol = "daml "
format = '[$symbol($version )]($style)'

[dart]
symbol = "dart "
format = '[$symbol($version )]($style)'

[deno]
symbol = "deno "
format = "'[$symbol($version )]($style)'"

[dotnet]
symbol = ".NET "
format = '[$symbol($version )( $tfm )]($style)'

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "
format = '[$symbol$context]($style) '

[elixir]
symbol = "exs "
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
symbol = "elm "
format = '[$symbol($version )]($style)'

[fennel]
symbol = "fnl "
format = '[$symbol($version )]($style)'

[fossil_branch]
symbol = "fossil "
format = '[$symbol$branch]($style) '

[gcloud]
symbol = "gcp "
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
symbol = "git "
format = '[$symbol$branch(:$remote_branch)]($style) '

[gleam]
symbol = "gleam "
format = '[$symbol($version )]($style)'

[golang]
symbol = "go "
format = '[$symbol($version )]($style)'

[gradle]
symbol = "gradle "
format = '[$symbol($version )]($style)'

[guix_shell]
symbol = "guix "
format = '[$symbol]($style) '

[hg_branch]
symbol = "hg "
format = '[$symbol$branch(:$topic)]($style) '

[java]
symbol = "java "
format = '[${symbol}(${version} )]($style)'

[julia]
symbol = "jl "
format = '[$symbol($version )]($style)'

[kotlin]
symbol = "kt "
format = '[$symbol($version )]($style)'

[lua]
symbol = "lua "
format = '[$symbol($version )]($style)'

[nodejs]
symbol = "nodejs "
format = '[$symbol($version )]($style)'

[memory_usage]
symbol = "memory "
format = '$symbol [${ram}( | ${swap})]($style) '

[meson]
symbol = "meson "
format = '[$symbol$project]($style) '

[nats]
symbol = "nats "

[nim]
symbol = "nim "
format = '[$symbol($version )]($style)'

[nix_shell]
symbol = "nix "
format = '[$symbol$state( \($name\))]($style) '

[ocaml]
symbol = "ml "
format = '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[opa]
symbol = "opa "
format = '[$symbol($version )]($style)'

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "
format = '[$symbol$version]($style) '

[perl]
symbol = "pl "
format = '[$symbol($version )]($style)'

[php]
symbol = "php "
format = '[$symbol($version )]($style)'

[pijul_channel]
symbol = "pijul "
format = '[$symbol$channel]($style) '

[pulumi]
symbol = "pulumi "
format = '[$symbol($username@)$stack]($style) '

[purescript]
symbol = "purs "
format = '[$symbol($version )]($style)'

[python]
symbol = "py "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[quarto]
symbol = "quarto "
format = '[$symbol($version )]($style)'

[raku]
symbol = "raku "
format = '[$symbol($version-$vm_version )]($style)'

[ruby]
symbol = "rb "
format = '[$symbol($version )]($style)'

[rust]
symbol = "rs "
format = '[$symbol($version )]($style)'

[scala]
symbol = "scala "
format = '[${symbol}(${version} )]($style)'

[spack]
symbol = "spack "
format = '[$symbol$environment]($style) '

[solidity]
symbol = "solidity "
format = '[$symbol($version )]($style)'

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "
format = '[$symbol]($style)'

[swift]
symbol = "swift "
format = '[$symbol($version )]($style)'

[typst]
symbol = "typst "
format = 'via [$symbol($version )]($style)'

[terraform]
symbol = "terraform "
format = '[$symbol$workspace]($style) '

[zig]
symbol = "zig "
format = '[$symbol($version )]($style)'